function [LiftDay,SquatDate,SquatMax,BenchPressDate,BenchPressMax,DeadliftDate,DeadliftMax] = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [LiftDay,SquatDate,SquatMax,BenchPressDate,BenchPressMax,DeadliftDate,DeadliftMax]
%   = IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [LiftDay,SquatDate,SquatMax,BenchPressDate,BenchPressMax,DeadliftDate,DeadliftMax]
%   = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [LiftDay,SquatDate,SquatMax,BenchPressDate,BenchPressMax,DeadliftDate,DeadliftMax]
%   = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [LiftDay,SquatDate,SquatMax,BenchPressDate,BenchPressMax,DeadliftDate,DeadliftMax] = importfile('Strength_ProgressData.xlsx','MainLiftLog',2,18);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/11/24 21:58:29

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 18;
end

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread(workbookFile, sheetName, sprintf('A%d:G%d',startRow(1),endRow(1)),'' , @convertSpreadsheetExcelDates);
for block=2:length(startRow)
    [~, ~, tmpRawBlock,tmpDateNumBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:G%d',startRow(block),endRow(block)),'' , @convertSpreadsheetExcelDates);
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
    dates = [dates;tmpDateNumBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
raw = raw(:,[1,3,5,7]);
dates = dates(:,[2,4,6]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),dates); % Find non-numeric cells
dates(R) = {NaN}; % Replace non-numeric Excel dates with NaN

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
LiftDay = data(:,1);
dates(~cellfun(@(x) isnumeric(x) || islogical(x), dates)) = {NaN};
SquatDate = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
SquatMax = data(:,2);
BenchPressDate = datetime([dates{:,2}].', 'ConvertFrom', 'Excel');
BenchPressMax = data(:,3);
DeadliftDate = datetime([dates{:,3}].', 'ConvertFrom', 'Excel');
DeadliftMax = data(:,4);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% SquatDate=datenum(SquatDate);
% BenchPressDate=datenum(BenchPressDate);
% DeadliftDate=datenum(DeadliftDate);

